In [6]:
import pandas as pd 

ds = pd.read_csv("data/processed/final.csv")
ds["datetime"] = pd.to_datetime(ds["datetime"])
ds["Yıl"] = ds["datetime"].dt.year

In [7]:
from scipy.stats import linregress
import pymannkendall as mk
import pandas as pd

# Yıllık bazda ortalama sıcaklık hesaplama
ds_yillik = ds.groupby(["Istasyon_No", "Yıl"])["t2m_avg"].mean().reset_index()

results = []
for istasyon, grup in ds_yillik.groupby("Istasyon_No"):
    # x değeri olarak yılları kullan
    slope, _, _, _, _ = linregress(grup["Yıl"], grup["t2m_avg"])
    mk_result = mk.original_test(grup["t2m_avg"])
    
    results.append({
        "Istasyon_No": istasyon,
        "Z_degeri": mk_result.z,
        "p_degeri": mk_result.p,
        "Egilim": mk_result.trend,
        "Sens_Slope": slope
    })

df_results = pd.DataFrame(results)

print(df_results)

    Istasyon_No  Z_degeri      p_degeri      Egilim  Sens_Slope
0         17238  3.807197  1.405506e-04  increasing    0.051491
1         17240  3.399283  6.756267e-04  increasing    0.048560
2         17255  5.064932  4.085456e-07  increasing    0.076866
3         17320  3.773205  1.611640e-04  increasing    0.044017
4         17330  4.011154  6.042258e-05  increasing    0.047005
5         17351  4.792990  1.643142e-06  increasing    0.058853
6         17355  3.841190  1.224392e-04  increasing    0.050839
7         17372  4.623025  3.781834e-06  increasing    0.053173
8         17375  3.603240  3.142746e-04  increasing    0.052773
9         17826  3.739212  1.845982e-04  increasing    0.053977
10        17828  3.467269  5.257753e-04  increasing    0.054290
11        17864  3.773205  1.611640e-04  increasing    0.055024
12        17866  3.943169  8.041204e-05  increasing    0.063276
13        17868  4.521047  6.153455e-06  increasing    0.081813
14        17870  4.623025  3.781834e-06  increasing    0.080791
15        17882  3.263312  1.101182e-03  increasing    0.049504
16        17892  4.283097  1.843097e-05  increasing    0.064889
17        17908  4.487054  7.221475e-06  increasing    0.063926
18        17926  3.365291  7.646309e-04  increasing    0.057125
19        17952  3.093348  1.979120e-03  increasing    0.048107
20        17954  3.127341  1.763954e-03  increasing    0.032799
21        17960  4.351083  1.354669e-05  increasing    0.056284
22        17974  3.977162  6.974278e-05  increasing    0.041175
23        17986  4.589033  4.453049e-06  increasing    0.048096

In [8]:
kendall = df_results[["Istasyon_No","Z_degeri", "p_degeri","Egilim"]]
senslope = df_results[["Istasyon_No","Sens_Slope"]]

In [9]:
kendall

    Istasyon_No  Z_degeri      p_degeri      Egilim
0         17238  3.807197  1.405506e-04  increasing
1         17240  3.399283  6.756267e-04  increasing
2         17255  5.064932  4.085456e-07  increasing
3         17320  3.773205  1.611640e-04  increasing
4         17330  4.011154  6.042258e-05  increasing
5         17351  4.792990  1.643142e-06  increasing
6         17355  3.841190  1.224392e-04  increasing
7         17372  4.623025  3.781834e-06  increasing
8         17375  3.603240  3.142746e-04  increasing
9         17826  3.739212  1.845982e-04  increasing
10        17828  3.467269  5.257753e-04  increasing
11        17864  3.773205  1.611640e-04  increasing
12        17866  3.943169  8.041204e-05  increasing
13        17868  4.521047  6.153455e-06  increasing
14        17870  4.623025  3.781834e-06  increasing
15        17882  3.263312  1.101182e-03  increasing
16        17892  4.283097  1.843097e-05  increasing
17        17908  4.487054  7.221475e-06  increasing
18        17926  3.365291  7.646309e-04  increasing
19        17952  3.093348  1.979120e-03  increasing
20        17954  3.127341  1.763954e-03  increasing
21        17960  4.351083  1.354669e-05  increasing
22        17974  3.977162  6.974278e-05  increasing
23        17986  4.589033  4.453049e-06  increasing

In [10]:
senslope

    Istasyon_No  Sens_Slope
0         17238    0.051491
1         17240    0.048560
2         17255    0.076866
3         17320    0.044017
4         17330    0.047005
5         17351    0.058853
6         17355    0.050839
7         17372    0.053173
8         17375    0.052773
9         17826    0.053977
10        17828    0.054290
11        17864    0.055024
12        17866    0.063276
13        17868    0.081813
14        17870    0.080791
15        17882    0.049504
16        17892    0.064889
17        17908    0.063926
18        17926    0.057125
19        17952    0.048107
20        17954    0.032799
21        17960    0.056284
22        17974    0.041175
23        17986    0.048096